GET http://localhost:3100/account/users

###

POST http://localhost:3100/account/iter
Content-Type: application/json

{
	"email": "test1@naver.com"
}

###

POST http://localhost:3100/account/session-iter
Content-Type: application/json

{
	"id": "53a10ad5-5c7a-4415-9683-a151b861b26d",
	"createdAt": 0
}

###

POST http://localhost:3100/account/check
Content-Type: application/json

{
	"email": "test1@naver.com",
	"nickname": "닉네임"
}
