get http://localhost:3000/example

###

get http://localhost:3000/companies

###

get http://localhost:3000/companies/:id

###

get http://localhost:3000/watches

###

get https://view-my-startup-codeit-be.onrender.com/example

###

get https://view-my-startup-codeit-be.onrender.com/companies

###

get https://view-my-startup-codeit-be.onrender.com/companies/2c1af571-b2eb-479a-b8c0-87ad911421f4?include=investments

###

get https://view-my-startup-codeit-be.onrender.com/watches